"""add oauth fields

Revision ID: 53a5476bff3e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 19:06:17.350315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a5476bff3e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_time'), table_name='activity')
    op.drop_index(op.f('ix_contacts_createdAt'), table_name='contacts')
    op.drop_index(op.f('ix_deals_createdAt'), table_name='deals')
    op.drop_index(op.f('ix_emails_sentAt'), table_name='emails')
    op.drop_index(op.f('ix_notes_createdAt'), table_name='notes')
    op.drop_index(op.f('ix_tasks_createdAt'), table_name='tasks')
    op.add_column('users', sa.Column('provider', sa.String(), server_default='local', nullable=False))
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'provider')
    op.create_index(op.f('ix_tasks_createdAt'), 'tasks', ['createdAt'], unique=False)
    op.create_index(op.f('ix_notes_createdAt'), 'notes', ['createdAt'], unique=False)
    op.create_index(op.f('ix_emails_sentAt'), 'emails', ['sentAt'], unique=False)
    op.create_index(op.f('ix_deals_createdAt'), 'deals', ['createdAt'], unique=False)
    op.create_index(op.f('ix_contacts_createdAt'), 'contacts', ['createdAt'], unique=False)
    op.create_index(op.f('ix_activity_time'), 'activity', ['time'], unique=False)
    # ### end Alembic commands ###
