"""Initial migration

Revision ID: c932eb470946
Revises: 
Create Date: 2026-03-10 16:16:23.772268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c932eb470946'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('activity', 'color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('contacts', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.alter_column('contacts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('contacts', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('contacts', 'linkedin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('contacts', 'updatedat')
    op.drop_column('contacts', 'createdat')
    op.add_column('deals', sa.Column('contactId', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('closeDate', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('deals', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.alter_column('deals', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('deals', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('deals', 'company',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('deals', 'value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('deals', 'stage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('deals', 'contactid')
    op.drop_column('deals', 'closedate')
    op.drop_column('deals', 'updatedat')
    op.drop_column('deals', 'createdat')
    op.add_column('emails', sa.Column('sentAt', sa.DateTime(), nullable=True))
    op.alter_column('emails', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('emails', 'to_email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('emails', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('emails', 'sentat')
    op.add_column('notes', sa.Column('contactId', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('contactName', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('updatedAt', sa.DateTime(), nullable=True))
    op.alter_column('notes', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notes', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('notes', 'contactname')
    op.drop_column('notes', 'updatedat')
    op.drop_column('notes', 'createdat')
    op.drop_column('notes', 'contactid')
    op.alter_column('settings', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('contactId', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('dueDate', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('tasks', 'contactid')
    op.drop_column('tasks', 'duedate')
    op.drop_column('tasks', 'createdat')
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('duedate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('contactid', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tasks', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('tasks', 'createdAt')
    op.drop_column('tasks', 'dueDate')
    op.drop_column('tasks', 'contactId')
    op.alter_column('settings', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('notes', sa.Column('contactid', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notes', sa.Column('contactname', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('notes', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notes', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('notes', 'updatedAt')
    op.drop_column('notes', 'createdAt')
    op.drop_column('notes', 'contactName')
    op.drop_column('notes', 'contactId')
    op.add_column('emails', sa.Column('sentat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('emails', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emails', 'to_email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('emails', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('emails', 'sentAt')
    op.add_column('deals', sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('closedate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('contactid', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('deals', 'stage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('deals', 'value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('deals', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('deals', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('deals', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('deals', 'updatedAt')
    op.drop_column('deals', 'createdAt')
    op.drop_column('deals', 'closeDate')
    op.drop_column('deals', 'contactId')
    op.add_column('contacts', sa.Column('createdat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('updatedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('contacts', 'linkedin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'company',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contacts', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('contacts', 'updatedAt')
    op.drop_column('contacts', 'createdAt')
    op.alter_column('activity', 'color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('activity', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
