"""Add subscription fields

Revision ID: e9b5f6704f0c
Revises: b2c3d4e5f6g7
Create Date: 2026-03-17 12:21:35.378939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b5f6704f0c'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_contactId'), table_name='emails')
    op.drop_index(op.f('ix_emails_direction'), table_name='emails')
    op.drop_index(op.f('ix_emails_trackingId'), table_name='emails')
    op.add_column('users', sa.Column('plan_name', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('subscription_status', sa.String(), server_default='active', nullable=False))
    op.add_column('users', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('razorpay_customer_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'razorpay_subscription_id')
    op.drop_column('users', 'razorpay_customer_id')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'plan_name')
    op.create_index(op.f('ix_emails_trackingId'), 'emails', ['trackingId'], unique=False)
    op.create_index(op.f('ix_emails_direction'), 'emails', ['direction'], unique=False)
    op.create_index(op.f('ix_emails_contactId'), 'emails', ['contactId'], unique=False)
    # ### end Alembic commands ###
